// This file is auto-generated by @hey-api/openapi-ts

export const AuctionSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        payment_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Method'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title', 'id', 'is_active', 'updated_on', 'created_on'],
    title: 'Auction'
} as const;

export const AuctionCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        payment_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Method'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'AuctionCreate'
} as const;

export const AuctionUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        payment_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Method'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'AuctionUpdate'
} as const;

export const BoatTypeSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title', 'id', 'updated_on', 'created_on'],
    title: 'BoatType'
} as const;

export const BoatTypeCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'BoatTypeCreate'
} as const;

export const BoatTypeUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'BoatTypeUpdate'
} as const;

export const BodyTypeSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title', 'id', 'updated_on', 'created_on'],
    title: 'BodyType'
} as const;

export const BodyTypeCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'BodyTypeCreate'
} as const;

export const BodyTypeUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'BodyTypeUpdate'
} as const;

export const CarBrandSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title', 'id', 'is_active', 'updated_on', 'created_on'],
    title: 'CarBrand'
} as const;

export const CarBrandCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CarBrandCreate'
} as const;

export const CarBrandUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CarBrandUpdate'
} as const;

export const CarModelSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        brand_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Id'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        brand: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CarBrand'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['title', 'id', 'is_active', 'updated_on', 'created_on'],
    title: 'CarModel'
} as const;

export const CarModelCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        brand_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Id'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CarModelCreate'
} as const;

export const CarModelUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        brand_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Id'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CarModelUpdate'
} as const;

export const CargoSchema = {
    properties: {
        vin_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vin Code'
        },
        year: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year',
            default: 2024
        },
        booking_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Booking Number'
        },
        carrier_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Carrier Title'
        },
        ship_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ship Title'
        },
        cost: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost',
            default: 0
        },
        auct_collect: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auct Collect',
            default: 0
        },
        penalty: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Penalty',
            default: 0
        },
        insurance_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Type',
            default: '0'
        },
        insurance_pay: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Pay',
            default: 0
        },
        sea_freight: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sea Freight',
            default: 0
        },
        land_delivery: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Land Delivery',
            default: 0
        },
        sublot: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sublot',
            default: 0
        },
        broker_sevice_amount: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Broker Sevice Amount',
            default: 0
        },
        storage_sevice_amount: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storage Sevice Amount',
            default: 0
        },
        is_closed_locat: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Closed Locat',
            default: false
        },
        closed_locat: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Closed Locat',
            default: 0
        },
        is_doc_change: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Doc Change',
            default: false
        },
        doc_change: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc Change',
            default: 0
        },
        container_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Container Id'
        },
        container: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Container'
                },
                {
                    type: 'null'
                }
            ]
        },
        port_from_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port From Id'
        },
        port_from: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortFrom'
                },
                {
                    type: 'null'
                }
            ]
        },
        port_to_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port To Id'
        },
        port_to: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortTo'
                },
                {
                    type: 'null'
                }
            ]
        },
        fuel_type_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fuel Type Id'
        },
        fuel_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FuelType'
                },
                {
                    type: 'null'
                }
            ]
        },
        engine_volume_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Engine Volume Id'
        },
        engine_volume: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EngineVolume'
                },
                {
                    type: 'null'
                }
            ]
        },
        body_type_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body Type Id'
        },
        body_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BodyType'
                },
                {
                    type: 'null'
                }
            ]
        },
        country_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Id'
        },
        country: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Country'
                },
                {
                    type: 'null'
                }
            ]
        },
        auction_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auction Id'
        },
        auction: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Auction'
                },
                {
                    type: 'null'
                }
            ]
        },
        transmission_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transmission Id'
        },
        transmission: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Transmission'
                },
                {
                    type: 'null'
                }
            ]
        },
        location_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Id'
        },
        location: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LocationFrom'
                },
                {
                    type: 'null'
                }
            ]
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['id', 'is_active', 'updated_on', 'created_on'],
    title: 'Cargo'
} as const;

export const CargoCreateSchema = {
    properties: {
        vin_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vin Code'
        },
        year: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year',
            default: 2024
        },
        booking_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Booking Number'
        },
        carrier_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Carrier Title'
        },
        ship_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ship Title'
        },
        cost: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost',
            default: 0
        },
        auct_collect: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auct Collect',
            default: 0
        },
        penalty: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Penalty',
            default: 0
        },
        insurance_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Type',
            default: '0'
        },
        insurance_pay: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Pay',
            default: 0
        },
        sea_freight: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sea Freight',
            default: 0
        },
        land_delivery: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Land Delivery',
            default: 0
        },
        sublot: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sublot',
            default: 0
        },
        broker_sevice_amount: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Broker Sevice Amount',
            default: 0
        },
        storage_sevice_amount: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storage Sevice Amount',
            default: 0
        },
        is_closed_locat: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Closed Locat',
            default: false
        },
        closed_locat: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Closed Locat',
            default: 0
        },
        is_doc_change: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Doc Change',
            default: false
        },
        doc_change: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc Change',
            default: 0
        },
        container_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Container Id'
        },
        container: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Container'
                },
                {
                    type: 'null'
                }
            ]
        },
        port_from_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port From Id'
        },
        port_from: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortFrom'
                },
                {
                    type: 'null'
                }
            ]
        },
        port_to_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port To Id'
        },
        port_to: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortTo'
                },
                {
                    type: 'null'
                }
            ]
        },
        fuel_type_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fuel Type Id'
        },
        fuel_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FuelType'
                },
                {
                    type: 'null'
                }
            ]
        },
        engine_volume_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Engine Volume Id'
        },
        engine_volume: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EngineVolume'
                },
                {
                    type: 'null'
                }
            ]
        },
        body_type_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body Type Id'
        },
        body_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BodyType'
                },
                {
                    type: 'null'
                }
            ]
        },
        country_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Id'
        },
        country: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Country'
                },
                {
                    type: 'null'
                }
            ]
        },
        auction_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auction Id'
        },
        auction: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Auction'
                },
                {
                    type: 'null'
                }
            ]
        },
        transmission_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transmission Id'
        },
        transmission: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Transmission'
                },
                {
                    type: 'null'
                }
            ]
        },
        location_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Id'
        },
        location: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LocationFrom'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'CargoCreate'
} as const;

export const CargoUpdateSchema = {
    properties: {
        vin_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vin Code'
        },
        year: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year',
            default: 2024
        },
        booking_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Booking Number'
        },
        carrier_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Carrier Title'
        },
        ship_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ship Title'
        },
        cost: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost',
            default: 0
        },
        auct_collect: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auct Collect',
            default: 0
        },
        penalty: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Penalty',
            default: 0
        },
        insurance_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Type',
            default: '0'
        },
        insurance_pay: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Insurance Pay',
            default: 0
        },
        sea_freight: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sea Freight',
            default: 0
        },
        land_delivery: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Land Delivery',
            default: 0
        },
        sublot: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sublot',
            default: 0
        },
        broker_sevice_amount: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Broker Sevice Amount',
            default: 0
        },
        storage_sevice_amount: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storage Sevice Amount',
            default: 0
        },
        is_closed_locat: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Closed Locat',
            default: false
        },
        closed_locat: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Closed Locat',
            default: 0
        },
        is_doc_change: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Doc Change',
            default: false
        },
        doc_change: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doc Change',
            default: 0
        },
        container_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Container Id'
        },
        container: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Container'
                },
                {
                    type: 'null'
                }
            ]
        },
        port_from_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port From Id'
        },
        port_from: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortFrom'
                },
                {
                    type: 'null'
                }
            ]
        },
        port_to_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port To Id'
        },
        port_to: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortTo'
                },
                {
                    type: 'null'
                }
            ]
        },
        fuel_type_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fuel Type Id'
        },
        fuel_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FuelType'
                },
                {
                    type: 'null'
                }
            ]
        },
        engine_volume_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Engine Volume Id'
        },
        engine_volume: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EngineVolume'
                },
                {
                    type: 'null'
                }
            ]
        },
        body_type_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body Type Id'
        },
        body_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BodyType'
                },
                {
                    type: 'null'
                }
            ]
        },
        country_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Id'
        },
        country: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Country'
                },
                {
                    type: 'null'
                }
            ]
        },
        auction_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auction Id'
        },
        auction: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Auction'
                },
                {
                    type: 'null'
                }
            ]
        },
        transmission_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transmission Id'
        },
        transmission: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Transmission'
                },
                {
                    type: 'null'
                }
            ]
        },
        location_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Id'
        },
        location: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LocationFrom'
                },
                {
                    type: 'null'
                }
            ]
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    title: 'CargoUpdate'
} as const;

export const CitySchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title', 'id', 'updated_on', 'created_on'],
    title: 'City'
} as const;

export const CityCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CityCreate'
} as const;

export const CityUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CityUpdate'
} as const;

export const ContainerSchema = {
    properties: {
        number: {
            type: 'string',
            title: 'Number'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['number', 'id', 'is_active', 'updated_on', 'created_on'],
    title: 'Container'
} as const;

export const ContainerCreateSchema = {
    properties: {
        number: {
            type: 'string',
            title: 'Number'
        }
    },
    type: 'object',
    required: ['number'],
    title: 'ContainerCreate'
} as const;

export const ContainerUpdateSchema = {
    properties: {
        number: {
            type: 'string',
            title: 'Number'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['number'],
    title: 'ContainerUpdate'
} as const;

export const CountrySchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            default: ''
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'Country'
} as const;

export const CountryCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            default: ''
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    title: 'CountryCreate'
} as const;

export const CountryUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            default: ''
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    title: 'CountryUpdate'
} as const;

export const EngineVolumeSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title', 'id', 'is_active', 'updated_on', 'created_on'],
    title: 'EngineVolume'
} as const;

export const EngineVolumeCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'EngineVolumeCreate'
} as const;

export const EngineVolumeUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'EngineVolumeUpdate'
} as const;

export const FuelTypeSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title', 'id', 'updated_on', 'created_on'],
    title: 'FuelType'
} as const;

export const FuelTypeCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'FuelTypeCreate'
} as const;

export const FuelTypeUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'FuelTypeUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LocationFromSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        port_ids: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port Ids',
            default: []
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title', 'id', 'is_active', 'updated_on', 'created_on'],
    title: 'LocationFrom'
} as const;

export const LocationFromCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        port_ids: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port Ids',
            default: []
        }
    },
    type: 'object',
    required: ['title'],
    title: 'LocationFromCreate'
} as const;

export const LocationFromUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        port_ids: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port Ids',
            default: []
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'LocationFromUpdate'
} as const;

export const OverlandTariffSchema = {
    properties: {
        price: {
            type: 'string',
            title: 'Price'
        },
        location_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Id'
        },
        port_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port Id'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        location: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LocationFrom'
                },
                {
                    type: 'null'
                }
            ]
        },
        port: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortFrom'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'is_active', 'updated_on', 'created_on'],
    title: 'OverlandTariff'
} as const;

export const OverlandTariffCreateSchema = {
    properties: {
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Price'
        },
        location_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Id'
        },
        port_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port Id'
        }
    },
    type: 'object',
    title: 'OverlandTariffCreate'
} as const;

export const OverlandTariffUpdateSchema = {
    properties: {
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Price'
        },
        location_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Id'
        },
        port_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port Id'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    title: 'OverlandTariffUpdate'
} as const;

export const OverseaTariffSchema = {
    properties: {
        price: {
            type: 'string',
            title: 'Price'
        },
        port_from_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port From Id'
        },
        port_to_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port To Id'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        port_from: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortFrom'
                },
                {
                    type: 'null'
                }
            ]
        },
        port_to: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortTo'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'is_active', 'updated_on', 'created_on'],
    title: 'OverseaTariff'
} as const;

export const OverseaTariffCreateSchema = {
    properties: {
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Price'
        },
        port_from_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port From Id'
        },
        port_to_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port To Id'
        }
    },
    type: 'object',
    title: 'OverseaTariffCreate'
} as const;

export const OverseaTariffUpdateSchema = {
    properties: {
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Price'
        },
        port_from_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port From Id'
        },
        port_to_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port To Id'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    title: 'OverseaTariffUpdate'
} as const;

export const PaginationSchema_BodyType_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/BodyType'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[BodyType]'
} as const;

export const PaginationSchema_CarBrand_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/CarBrand'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[CarBrand]'
} as const;

export const PaginationSchema_CarModel_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/CarModel'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[CarModel]'
} as const;

export const PaginationSchema_Cargo_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/Cargo'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[Cargo]'
} as const;

export const PaginationSchema_City_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/City'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[City]'
} as const;

export const PaginationSchema_Container_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/Container'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[Container]'
} as const;

export const PaginationSchema_Country_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/Country'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[Country]'
} as const;

export const PaginationSchema_EngineVolume_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/EngineVolume'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[EngineVolume]'
} as const;

export const PaginationSchema_FuelType_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/FuelType'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[FuelType]'
} as const;

export const PaginationSchema_LocationFrom_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/LocationFrom'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[LocationFrom]'
} as const;

export const PaginationSchema_OverlandTariff_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/OverlandTariff'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[OverlandTariff]'
} as const;

export const PaginationSchema_OverseaTariff_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/OverseaTariff'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[OverseaTariff]'
} as const;

export const PaginationSchema_PortFrom_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/PortFrom'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[PortFrom]'
} as const;

export const PaginationSchema_PortTo_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/PortTo'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[PortTo]'
} as const;

export const PaginationSchema_Transmission_Schema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/Transmission'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total', 'page', 'total_pages', 'items'],
    title: 'PaginationSchema[Transmission]'
} as const;

export const PortFromSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        zipcode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Zipcode'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title', 'id', 'is_active', 'updated_on', 'created_on'],
    title: 'PortFrom'
} as const;

export const PortFromCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        zipcode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Zipcode'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'PortFromCreate'
} as const;

export const PortFromUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        zipcode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Zipcode'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'PortFromUpdate'
} as const;

export const PortToSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        country_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Id'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        country: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Country'
                },
                {
                    type: 'null'
                }
            ]
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'PortTo'
} as const;

export const PortToCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        country_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Id'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'PortToCreate'
} as const;

export const PortToUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        country_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Id'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'PortToUpdate'
} as const;

export const TransmissionSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        }
    },
    type: 'object',
    required: ['title', 'id', 'updated_on', 'created_on'],
    title: 'Transmission'
} as const;

export const TransmissionCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'TransmissionCreate'
} as const;

export const TransmissionUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'TransmissionUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;