// This file is auto-generated by @hey-api/openapi-ts

export type AdminUserUpdate = {
    email?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    phone_number?: (string | null);
    role?: (UserRole | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type UserRole = 'Admin' | 'Manager' | 'Accountant' | 'Dealer' | 'Logistician' | 'Broker' | 'Customer';

export type UserSignin = {
    email: string;
    password: string;
};

export type UserSignup = {
    email: string;
    password: string;
    first_name?: (string | null);
    last_name?: (string | null);
};

export type UserUpdate = {
    email?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    phone_number?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RegisterAccountApiV1AuthPostResponse = (unknown);

export type RegisterAccountApiV1AuthPostError = unknown;

export type SignupUserApiV1AuthSignupPostData = {
    body: UserSignup;
};

export type SignupUserApiV1AuthSignupPostResponse = (unknown);

export type SignupUserApiV1AuthSignupPostError = (HTTPValidationError);

export type SigninUserApiV1AuthSigninPostData = {
    body: UserSignin;
};

export type SigninUserApiV1AuthSigninPostResponse = (unknown);

export type SigninUserApiV1AuthSigninPostError = (HTTPValidationError);

export type ChangeMeApiV1AuthChangePatchData = {
    body: UserUpdate;
};

export type ChangeMeApiV1AuthChangePatchResponse = (unknown);

export type ChangeMeApiV1AuthChangePatchError = (HTTPValidationError);

export type GetMeApiV1AuthMeGetResponse = (unknown);

export type GetMeApiV1AuthMeGetError = unknown;

export type ChangeUserApiV1AuthChangeUserIdPatchData = {
    body?: (AdminUserUpdate);
    path: {
        user_id: string;
    };
};

export type ChangeUserApiV1AuthChangeUserIdPatchResponse = (unknown);

export type ChangeUserApiV1AuthChangeUserIdPatchError = (HTTPValidationError);

export type CheckUserRoleApiV1AuthCheckRoleUserIdGetResponse = (unknown);

export type CheckUserRoleApiV1AuthCheckRoleUserIdGetError = unknown;

export type RootGetResponse = (unknown);

export type RootGetError = unknown;