// This file is auto-generated by @hey-api/openapi-ts

export type AdminUserInfo = {
    id?: (string);
    email?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    phone_number?: (string | null);
    role?: (UserRole | null);
    email_verified?: (boolean | null);
    phone?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type PaginationSchema_AdminUserInfo_ = {
    total: number;
    page: number;
    total_pages: number;
    items: Array<AdminUserInfo>;
};

export type SignInUserInfo = {
    access_token: string;
    refresh_token: string;
    id_token: string;
    user_info: UserInfo;
};

export type UserInfo = {
    id?: (string);
    email?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    phone_number?: (string | null);
    role?: (UserRole | null);
};

export type UserRole = 'Admin' | 'Manager' | 'Accountant' | 'Dealer' | 'Logistician' | 'Broker' | 'Customer';

export type UserSignin = {
    email: string;
    password: string;
};

export type UserSignup = {
    email: string;
    password: string;
    first_name?: (string | null);
    last_name?: (string | null);
};

export type UserUpdate = {
    email?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    phone_number?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RegisterAccountApiV1AuthPostResponse = (unknown);

export type RegisterAccountApiV1AuthPostError = unknown;

export type SignupUserApiV1AuthSignupPostData = {
    body: UserSignup;
};

export type SignupUserApiV1AuthSignupPostResponse = (SignInUserInfo);

export type SignupUserApiV1AuthSignupPostError = (HTTPValidationError);

export type SigninUserApiV1AuthSigninPostData = {
    body: UserSignin;
};

export type SigninUserApiV1AuthSigninPostResponse = (unknown);

export type SigninUserApiV1AuthSigninPostError = (HTTPValidationError);

export type ChangeMeApiV1AuthChangePatchData = {
    body: UserUpdate;
};

export type ChangeMeApiV1AuthChangePatchResponse = (unknown);

export type ChangeMeApiV1AuthChangePatchError = (HTTPValidationError);

export type GetMeApiV1AuthMeGetResponse = (UserInfo);

export type GetMeApiV1AuthMeGetError = unknown;

export type AdminGetUsersApiV1UsersGetData = {
    query?: {
        page?: number;
        search?: string;
    };
};

export type AdminGetUsersApiV1UsersGetResponse = (PaginationSchema_AdminUserInfo_);

export type AdminGetUsersApiV1UsersGetError = (HTTPValidationError);

export type AdminGetUserApiV1UsersUserIdGetData = {
    path: {
        user_id: string;
    };
};

export type AdminGetUserApiV1UsersUserIdGetResponse = (AdminUserInfo);

export type AdminGetUserApiV1UsersUserIdGetError = (HTTPValidationError);

export type ChangeUserApiV1UsersChangeUserIdPatchData = {
    body?: (AdminUserInfo);
    headers?: {
        Authorization?: string;
    };
    path: {
        user_id: string;
    };
};

export type ChangeUserApiV1UsersChangeUserIdPatchResponse = (AdminUserInfo);

export type ChangeUserApiV1UsersChangeUserIdPatchError = (HTTPValidationError);

export type RootGetResponse = (unknown);

export type RootGetError = unknown;