// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { GetUserBalanceApiV1UserBalanceGetData, GetUserBalanceApiV1UserBalanceGetError, GetUserBalanceApiV1UserBalanceGetResponse, GetUserBalanceApiV1UserBalanceUsersBalancesGetData, GetUserBalanceApiV1UserBalanceUsersBalancesGetError, GetUserBalanceApiV1UserBalanceUsersBalancesGetResponse, GetUserBalanceApiV1UserBalanceUserIdGetData, GetUserBalanceApiV1UserBalanceUserIdGetError, GetUserBalanceApiV1UserBalanceUserIdGetResponse, GetCargosApiV1CargoGetData, GetCargosApiV1CargoGetError, GetCargosApiV1CargoGetResponse, CreateCargoApiV1CargoPostData, CreateCargoApiV1CargoPostError, CreateCargoApiV1CargoPostResponse, GetCargoApiV1CargoCargoIdGetData, GetCargoApiV1CargoCargoIdGetError, GetCargoApiV1CargoCargoIdGetResponse, UpdateCargoApiV1CargoCargoIdPutData, UpdateCargoApiV1CargoCargoIdPutError, UpdateCargoApiV1CargoCargoIdPutResponse, PayForCargoApiV1CargoPayCargoIdPostData, PayForCargoApiV1CargoPayCargoIdPostError, PayForCargoApiV1CargoPayCargoIdPostResponse, GetTransactionsApiV1TransactionsGetData, GetTransactionsApiV1TransactionsGetError, GetTransactionsApiV1TransactionsGetResponse, GetSingleTransactionApiV1TransactionsTransactionIdGetData, GetSingleTransactionApiV1TransactionsTransactionIdGetError, GetSingleTransactionApiV1TransactionsTransactionIdGetResponse, RootGetError, RootGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get User Balance
 */
export const getUserBalanceApiV1UserBalanceGet = <ThrowOnError extends boolean = false>(options: Options<GetUserBalanceApiV1UserBalanceGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserBalanceApiV1UserBalanceGetResponse, GetUserBalanceApiV1UserBalanceGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/user-balance/'
    });
};

/**
 * Get User Balance
 */
export const getUserBalanceApiV1UserBalanceUsersBalancesGet = <ThrowOnError extends boolean = false>(options?: Options<GetUserBalanceApiV1UserBalanceUsersBalancesGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserBalanceApiV1UserBalanceUsersBalancesGetResponse, GetUserBalanceApiV1UserBalanceUsersBalancesGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/user-balance/users_balances/'
    });
};

/**
 * Get User Balance
 */
export const getUserBalanceApiV1UserBalanceUserIdGet = <ThrowOnError extends boolean = false>(options: Options<GetUserBalanceApiV1UserBalanceUserIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserBalanceApiV1UserBalanceUserIdGetResponse, GetUserBalanceApiV1UserBalanceUserIdGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/user-balance/{user_id}/'
    });
};

/**
 * Get Cargos
 */
export const getCargosApiV1CargoGet = <ThrowOnError extends boolean = false>(options?: Options<GetCargosApiV1CargoGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCargosApiV1CargoGetResponse, GetCargosApiV1CargoGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/cargo/'
    });
};

/**
 * Create Cargo
 */
export const createCargoApiV1CargoPost = <ThrowOnError extends boolean = false>(options: Options<CreateCargoApiV1CargoPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateCargoApiV1CargoPostResponse, CreateCargoApiV1CargoPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/cargo/'
    });
};

/**
 * Get Cargo
 */
export const getCargoApiV1CargoCargoIdGet = <ThrowOnError extends boolean = false>(options: Options<GetCargoApiV1CargoCargoIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCargoApiV1CargoCargoIdGetResponse, GetCargoApiV1CargoCargoIdGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/cargo/{cargo_id}/'
    });
};

/**
 * Update Cargo
 */
export const updateCargoApiV1CargoCargoIdPut = <ThrowOnError extends boolean = false>(options: Options<UpdateCargoApiV1CargoCargoIdPutData, ThrowOnError>) => {
    return (options?.client ?? client).put<UpdateCargoApiV1CargoCargoIdPutResponse, UpdateCargoApiV1CargoCargoIdPutError, ThrowOnError>({
        ...options,
        url: '/api/v1/cargo/{cargo_id}/'
    });
};

/**
 * Pay For Cargo
 */
export const payForCargoApiV1CargoPayCargoIdPost = <ThrowOnError extends boolean = false>(options: Options<PayForCargoApiV1CargoPayCargoIdPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<PayForCargoApiV1CargoPayCargoIdPostResponse, PayForCargoApiV1CargoPayCargoIdPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/cargo/pay/{cargo_id}/'
    });
};

/**
 * Get Transactions
 */
export const getTransactionsApiV1TransactionsGet = <ThrowOnError extends boolean = false>(options?: Options<GetTransactionsApiV1TransactionsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTransactionsApiV1TransactionsGetResponse, GetTransactionsApiV1TransactionsGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/transactions/'
    });
};

/**
 * Get Single Transaction
 */
export const getSingleTransactionApiV1TransactionsTransactionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetSingleTransactionApiV1TransactionsTransactionIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetSingleTransactionApiV1TransactionsTransactionIdGetResponse, GetSingleTransactionApiV1TransactionsTransactionIdGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/transactions/{transaction_id}/'
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<RootGetResponse, RootGetError, ThrowOnError>({
        ...options,
        url: '/'
    });
};