// This file is auto-generated by @hey-api/openapi-ts

export type ApprovePayment = {
    amount: number;
    status: PAYMENT_STATUS;
};

export type CargoPaySchema = {
    amount: number;
};

export type CargoSchema = {
    vin_code?: (string | null);
    cost?: (number | null);
    sublot?: (number | null);
    auct_collect?: (number | null);
    penalty?: (number | null);
    insurance_pay?: (number | null);
    sea_freight?: (number | null);
    land_delivery?: (number | null);
    broker_sevice_amount?: (number | null);
    storage_sevice_amount?: (number | null);
    doc_change_cost?: (number | null);
    closed_location_cost?: (number | null);
    total_amount?: (number | null);
    paid_amount?: (number | null);
    id: number;
    dealer_id?: (string | null);
    left_to_pay_amount?: (number | null);
};

export type CargoUpdateSchema = {
    vin_code?: (string | null);
    cost?: (number | null);
    sublot?: (number | null);
    auct_collect?: (number | null);
    penalty?: (number | null);
    insurance_pay?: (number | null);
    sea_freight?: (number | null);
    land_delivery?: (number | null);
    broker_sevice_amount?: (number | null);
    storage_sevice_amount?: (number | null);
    doc_change_cost?: (number | null);
    closed_location_cost?: (number | null);
    total_amount?: (number | null);
    paid_amount?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type PAYMENT_STATUS = 'new' | 'approving' | 'approved' | 'failed';

export type PaginationSchema_Payment_ = {
    total: number;
    page: number;
    total_pages: number;
    items: Array<Payment>;
};

export type PaginationSchema_Transaction_ = {
    total: number;
    page: number;
    total_pages: number;
    items: Array<Transaction>;
};

export type PayCargoResponse = {
    success: boolean;
    amount: number;
};

export type Payment = {
    id: number;
    user_id: string;
    amount: number;
    file_path: (string | null);
    payment_date: string;
    status: string;
    is_active: boolean;
    updated_on: string;
    created_on: string;
};

export type Transaction = {
    created_by_user_id: string;
    created_by_user_role: UserRole;
    user_id: string;
    amount: number;
    balance_before: number;
    balance_after: number;
    cargo_id: (number | null);
    cargo: (CargoSchema | null);
    updated_on: string;
    created_on: string;
};

export type UserBalance = {
    user_id: string;
    balance: number;
};

export type UserRole = 'Admin' | 'Manager' | 'Accountant' | 'Dealer' | 'Logistician' | 'Broker' | 'Customer' | 'Robot';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetUserBalanceApiV1UserBalanceGetData = {
    query: {
        token: string;
    };
};

export type GetUserBalanceApiV1UserBalanceGetResponse = (UserBalance);

export type GetUserBalanceApiV1UserBalanceGetError = (HTTPValidationError);

export type GetUserBalanceApiV1UserBalanceUsersBalancesGetData = {
    query?: {
        user_ids?: Array<(string)>;
    };
};

export type GetUserBalanceApiV1UserBalanceUsersBalancesGetResponse = (Array<UserBalance>);

export type GetUserBalanceApiV1UserBalanceUsersBalancesGetError = (HTTPValidationError);

export type GetUserBalanceApiV1UserBalanceUserIdGetData = {
    path: {
        user_id: string;
    };
};

export type GetUserBalanceApiV1UserBalanceUserIdGetResponse = (UserBalance);

export type GetUserBalanceApiV1UserBalanceUserIdGetError = (HTTPValidationError);

export type GetCargosApiV1CargoGetData = {
    query?: {
        cargo_ids?: string;
    };
};

export type GetCargosApiV1CargoGetResponse = (Array<CargoSchema>);

export type GetCargosApiV1CargoGetError = (HTTPValidationError);

export type CreateCargoApiV1CargoPostData = {
    body: CargoSchema;
};

export type CreateCargoApiV1CargoPostResponse = (CargoSchema);

export type CreateCargoApiV1CargoPostError = (HTTPValidationError);

export type GetCargoApiV1CargoCargoIdGetData = {
    path: {
        cargo_id: number;
    };
};

export type GetCargoApiV1CargoCargoIdGetResponse = (CargoSchema);

export type GetCargoApiV1CargoCargoIdGetError = (HTTPValidationError);

export type UpdateCargoApiV1CargoCargoIdPutData = {
    body: CargoUpdateSchema;
    path: {
        cargo_id: number;
    };
};

export type UpdateCargoApiV1CargoCargoIdPutResponse = (CargoSchema);

export type UpdateCargoApiV1CargoCargoIdPutError = (HTTPValidationError);

export type PayForCargoApiV1CargoPayCargoIdPostData = {
    body: CargoPaySchema;
    path: {
        cargo_id: number;
    };
};

export type PayForCargoApiV1CargoPayCargoIdPostResponse = (PayCargoResponse);

export type PayForCargoApiV1CargoPayCargoIdPostError = (HTTPValidationError);

export type GetTransactionsApiV1TransactionsGetData = {
    query?: {
        cargo_id?: number;
        user_id?: string;
    };
};

export type GetTransactionsApiV1TransactionsGetResponse = (PaginationSchema_Transaction_);

export type GetTransactionsApiV1TransactionsGetError = (HTTPValidationError);

export type GetSingleTransactionApiV1TransactionsTransactionIdGetData = {
    path: {
        transaction_id: number;
    };
};

export type GetSingleTransactionApiV1TransactionsTransactionIdGetResponse = (Transaction);

export type GetSingleTransactionApiV1TransactionsTransactionIdGetError = (HTTPValidationError);

export type GetAllPaymentsApiV1PaymentsAccountantGetData = {
    query?: {
        status?: (PAYMENT_STATUS);
        user_id?: string;
    };
};

export type GetAllPaymentsApiV1PaymentsAccountantGetResponse = (PaginationSchema_Payment_);

export type GetAllPaymentsApiV1PaymentsAccountantGetError = (HTTPValidationError);

export type GetSinglePaymentApiV1PaymentsAccountantPaymentIdGetData = {
    path: {
        payment_id: number;
    };
};

export type GetSinglePaymentApiV1PaymentsAccountantPaymentIdGetResponse = (Payment);

export type GetSinglePaymentApiV1PaymentsAccountantPaymentIdGetError = (HTTPValidationError);

export type ProcessPaymentApiV1PaymentsAccountantPaymentIdPostData = {
    body: ApprovePayment;
    path: {
        payment_id: number;
    };
};

export type ProcessPaymentApiV1PaymentsAccountantPaymentIdPostResponse = (Payment);

export type ProcessPaymentApiV1PaymentsAccountantPaymentIdPostError = (HTTPValidationError);

export type GetMyPaymentsApiV1PaymentsDealerGetData = {
    query: {
        token: string;
    };
};

export type GetMyPaymentsApiV1PaymentsDealerGetResponse = (Payment);

export type GetMyPaymentsApiV1PaymentsDealerGetError = (HTTPValidationError);

export type GetMySinglePaymentApiV1PaymentsDealerPaymentIdGetData = {
    path: {
        payment_id: string;
    };
};

export type GetMySinglePaymentApiV1PaymentsDealerPaymentIdGetResponse = (Payment);

export type GetMySinglePaymentApiV1PaymentsDealerPaymentIdGetError = (HTTPValidationError);

export type GetSinglePaymentApiV1PaymentsAdminPaymentIdPostData = {
    body: ApprovePayment;
    path: {
        payment_id: number;
    };
};

export type GetSinglePaymentApiV1PaymentsAdminPaymentIdPostResponse = (Payment);

export type GetSinglePaymentApiV1PaymentsAdminPaymentIdPostError = (HTTPValidationError);

export type RootGetResponse = (unknown);

export type RootGetError = unknown;