// This file is auto-generated by @hey-api/openapi-ts

export const Body_upload_file_api_v1_cargo_docs__cargo_id___postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_file_api_v1_cargo_docs__cargo_id___post'
} as const;

export const Body_upload_file_api_v1_images__vin_code___postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_file_api_v1_images__vin_code___post'
} as const;

export const Body_upload_file_container_api_v1_containers__postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_file_container_api_v1_containers__post'
} as const;

export const Body_upload_file_duty_api_v1_duties__cargo_id___postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_file_duty_api_v1_duties__cargo_id___post'
} as const;

export const Body_upload_file_invoice_api_v1_invoices__cargo_id___postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_file_invoice_api_v1_invoices__cargo_id___post'
} as const;

export const Body_upload_file_payment_api_v1_payments__postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_file_payment_api_v1_payments__post'
} as const;

export const Body_upload_multiple_files_api_v1_cargo_docs__cargo_id__multiple__postSchema = {
    properties: {
        files: {
            items: {
                type: 'string',
                format: 'binary'
            },
            type: 'array',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['files'],
    title: 'Body_upload_multiple_files_api_v1_cargo_docs__cargo_id__multiple__post'
} as const;

export const Body_upload_multiple_files_api_v1_images__vin_code__multiple__postSchema = {
    properties: {
        files: {
            items: {
                type: 'string',
                format: 'binary'
            },
            type: 'array',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['files'],
    title: 'Body_upload_multiple_files_api_v1_images__vin_code__multiple__post'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImageUploadResponseSchema = {
    properties: {
        filename: {
            type: 'string',
            title: 'Filename'
        }
    },
    type: 'object',
    required: ['filename'],
    title: 'ImageUploadResponse'
} as const;

export const MultiImageUploadResponseSchema = {
    properties: {
        filenames: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Filenames'
        }
    },
    type: 'object',
    required: ['filenames'],
    title: 'MultiImageUploadResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;