// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options, formDataBodySerializer } from '@hey-api/client-axios';
import type { UploadFileApiV1ImagesVinCodePostData, UploadFileApiV1ImagesVinCodePostError, UploadFileApiV1ImagesVinCodePostResponse, GetFileApiV1ImagesVinCodeGetData, GetFileApiV1ImagesVinCodeGetError, GetFileApiV1ImagesVinCodeGetResponse, GetFileApiV1ImagesVinCodeFilenameGetData, GetFileApiV1ImagesVinCodeFilenameGetError, GetFileApiV1ImagesVinCodeFilenameGetResponse, DeleteFileApiV1ImagesVinCodeFilenameDeleteData, DeleteFileApiV1ImagesVinCodeFilenameDeleteError, DeleteFileApiV1ImagesVinCodeFilenameDeleteResponse, RootGetError, RootGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Upload File
 */
export const uploadFileApiV1ImagesVinCodePost = <ThrowOnError extends boolean = false>(options: Options<UploadFileApiV1ImagesVinCodePostData, ThrowOnError>) => {
    return (options?.client ?? client).post<UploadFileApiV1ImagesVinCodePostResponse, UploadFileApiV1ImagesVinCodePostError, ThrowOnError>({
        ...options,
        ...formDataBodySerializer,
        headers: {
            'Content-Type': null,
            ...options?.headers
        },
        url: '/api/v1/images/{vin_code}/'
    });
};

/**
 * Get File
 */
export const getFileApiV1ImagesVinCodeGet = <ThrowOnError extends boolean = false>(options: Options<GetFileApiV1ImagesVinCodeGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFileApiV1ImagesVinCodeGetResponse, GetFileApiV1ImagesVinCodeGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/images/{vin_code}/'
    });
};

/**
 * Get File
 */
export const getFileApiV1ImagesVinCodeFilenameGet = <ThrowOnError extends boolean = false>(options: Options<GetFileApiV1ImagesVinCodeFilenameGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFileApiV1ImagesVinCodeFilenameGetResponse, GetFileApiV1ImagesVinCodeFilenameGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/images/{vin_code}/{filename}/'
    });
};

/**
 * Delete File
 */
export const deleteFileApiV1ImagesVinCodeFilenameDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteFileApiV1ImagesVinCodeFilenameDeleteData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteFileApiV1ImagesVinCodeFilenameDeleteResponse, DeleteFileApiV1ImagesVinCodeFilenameDeleteError, ThrowOnError>({
        ...options,
        url: '/api/v1/images/{vin_code}/{filename}/'
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<RootGetResponse, RootGetError, ThrowOnError>({
        ...options,
        url: '/'
    });
};