// This file is auto-generated by @hey-api/openapi-ts

export type Body_upload_file_api_v1_cargo_docs__cargo_id___post = {
    file: (Blob | File);
};

export type Body_upload_file_api_v1_images__vin_code___post = {
    file: (Blob | File);
};

export type Body_upload_file_duty_api_v1_duties__cargo_id___post = {
    file: (Blob | File);
};

export type Body_upload_file_invoice_api_v1_invoices__cargo_id___post = {
    file: (Blob | File);
};

export type Body_upload_file_payment_api_v1_payments__post = {
    file: (Blob | File);
};

export type Body_upload_multiple_files_api_v1_cargo_docs__cargo_id__multiple__post = {
    files: Array<((Blob | File))>;
};

export type Body_upload_multiple_files_api_v1_images__vin_code__multiple__post = {
    files: Array<((Blob | File))>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImageUploadResponse = {
    filename: string;
};

export type MultiImageUploadResponse = {
    filenames: Array<(string)>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type UploadFileApiV1ImagesVinCodePostData = {
    body: Body_upload_file_api_v1_images__vin_code___post;
    path: {
        vin_code: string;
    };
};

export type UploadFileApiV1ImagesVinCodePostResponse = (ImageUploadResponse);

export type UploadFileApiV1ImagesVinCodePostError = (HTTPValidationError);

export type GetFilesApiV1ImagesVinCodeGetData = {
    path: {
        vin_code: string;
    };
};

export type GetFilesApiV1ImagesVinCodeGetResponse = (Array<(string)>);

export type GetFilesApiV1ImagesVinCodeGetError = (HTTPValidationError);

export type UploadMultipleFilesApiV1ImagesVinCodeMultiplePostData = {
    body: Body_upload_multiple_files_api_v1_images__vin_code__multiple__post;
    path: {
        vin_code: string;
    };
};

export type UploadMultipleFilesApiV1ImagesVinCodeMultiplePostResponse = (MultiImageUploadResponse);

export type UploadMultipleFilesApiV1ImagesVinCodeMultiplePostError = (HTTPValidationError);

export type GetFileApiV1ImagesVinCodeFilenameGetData = {
    path: {
        filename: string;
        vin_code: string;
    };
};

export type GetFileApiV1ImagesVinCodeFilenameGetResponse = (unknown);

export type GetFileApiV1ImagesVinCodeFilenameGetError = (HTTPValidationError);

export type DeleteFileApiV1ImagesVinCodeFilenameDeleteData = {
    path: {
        filename: string;
        vin_code: string;
    };
};

export type DeleteFileApiV1ImagesVinCodeFilenameDeleteResponse = (unknown);

export type DeleteFileApiV1ImagesVinCodeFilenameDeleteError = (HTTPValidationError);

export type UploadFileDutyApiV1DutiesCargoIdPostData = {
    body: Body_upload_file_duty_api_v1_duties__cargo_id___post;
    path: {
        cargo_id: string;
    };
};

export type UploadFileDutyApiV1DutiesCargoIdPostResponse = (ImageUploadResponse);

export type UploadFileDutyApiV1DutiesCargoIdPostError = (HTTPValidationError);

export type GetFileDutyApiV1DutiesCargoIdFilenameGetData = {
    path: {
        cargo_id: string;
        filename: string;
    };
};

export type GetFileDutyApiV1DutiesCargoIdFilenameGetResponse = (unknown);

export type GetFileDutyApiV1DutiesCargoIdFilenameGetError = (HTTPValidationError);

export type UploadFileApiV1CargoDocsCargoIdPostData = {
    body: Body_upload_file_api_v1_cargo_docs__cargo_id___post;
    path: {
        cargo_id: number;
    };
};

export type UploadFileApiV1CargoDocsCargoIdPostResponse = (ImageUploadResponse);

export type UploadFileApiV1CargoDocsCargoIdPostError = (HTTPValidationError);

export type GetFilesApiV1CargoDocsCargoIdGetData = {
    path: {
        cargo_id: number;
    };
};

export type GetFilesApiV1CargoDocsCargoIdGetResponse = (Array<(string)>);

export type GetFilesApiV1CargoDocsCargoIdGetError = (HTTPValidationError);

export type UploadMultipleFilesApiV1CargoDocsCargoIdMultiplePostData = {
    body: Body_upload_multiple_files_api_v1_cargo_docs__cargo_id__multiple__post;
    path: {
        cargo_id: number;
    };
};

export type UploadMultipleFilesApiV1CargoDocsCargoIdMultiplePostResponse = (MultiImageUploadResponse);

export type UploadMultipleFilesApiV1CargoDocsCargoIdMultiplePostError = (HTTPValidationError);

export type GetFileApiV1CargoDocsCargoIdFilenameGetData = {
    path: {
        cargo_id: number;
        filename: string;
    };
};

export type GetFileApiV1CargoDocsCargoIdFilenameGetResponse = (unknown);

export type GetFileApiV1CargoDocsCargoIdFilenameGetError = (HTTPValidationError);

export type DeleteFileApiV1CargoDocsCargoIdFilenameDeleteData = {
    path: {
        cargo_id: number;
        filename: string;
    };
};

export type DeleteFileApiV1CargoDocsCargoIdFilenameDeleteResponse = (unknown);

export type DeleteFileApiV1CargoDocsCargoIdFilenameDeleteError = (HTTPValidationError);

export type UploadFileInvoiceApiV1InvoicesCargoIdPostData = {
    body: Body_upload_file_invoice_api_v1_invoices__cargo_id___post;
    path: {
        cargo_id: string;
    };
};

export type UploadFileInvoiceApiV1InvoicesCargoIdPostResponse = (ImageUploadResponse);

export type UploadFileInvoiceApiV1InvoicesCargoIdPostError = (HTTPValidationError);

export type GetFileInvoiceApiV1InvoicesCargoIdFilenameGetData = {
    path: {
        cargo_id: string;
        filename: string;
    };
};

export type GetFileInvoiceApiV1InvoicesCargoIdFilenameGetResponse = (unknown);

export type GetFileInvoiceApiV1InvoicesCargoIdFilenameGetError = (HTTPValidationError);

export type UploadFilePaymentApiV1PaymentsPostData = {
    body: Body_upload_file_payment_api_v1_payments__post;
};

export type UploadFilePaymentApiV1PaymentsPostResponse = (ImageUploadResponse);

export type UploadFilePaymentApiV1PaymentsPostError = (HTTPValidationError);

export type GetFilePaymentApiV1PaymentsPaymentIdFilenameGetData = {
    path: {
        filename: string;
        payment_id: number;
    };
};

export type GetFilePaymentApiV1PaymentsPaymentIdFilenameGetResponse = (unknown);

export type GetFilePaymentApiV1PaymentsPaymentIdFilenameGetError = (HTTPValidationError);

export type GetFilePaymentApiV1PaymentsDealerFilenameGetData = {
    path: {
        filename: string;
    };
};

export type GetFilePaymentApiV1PaymentsDealerFilenameGetResponse = (unknown);

export type GetFilePaymentApiV1PaymentsDealerFilenameGetError = (HTTPValidationError);

export type GetFilePaymentApiV1PaymentsAccountantUserIdFilenameGetData = {
    path: {
        filename: string;
        user_id: string;
    };
};

export type GetFilePaymentApiV1PaymentsAccountantUserIdFilenameGetResponse = (unknown);

export type GetFilePaymentApiV1PaymentsAccountantUserIdFilenameGetError = (HTTPValidationError);

export type RootGetResponse = (unknown);

export type RootGetError = unknown;