// This file is auto-generated by @hey-api/openapi-ts

export type Body_upload_file_api_v1_images__vin_code___post = {
    file: (Blob | File);
};

export type Body_upload_multiple_files_api_v1_images__vin_code__multiple__post = {
    files: Array<((Blob | File))>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImageUploadResponse = {
    filename: string;
};

export type MultiImageUploadResponse = {
    filenames: Array<(string)>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type UploadFileApiV1ImagesVinCodePostData = {
    body: Body_upload_file_api_v1_images__vin_code___post;
    path: {
        vin_code: string;
    };
};

export type UploadFileApiV1ImagesVinCodePostResponse = (ImageUploadResponse);

export type UploadFileApiV1ImagesVinCodePostError = (HTTPValidationError);

export type GetFilesApiV1ImagesVinCodeGetData = {
    path: {
        vin_code: string;
    };
};

export type GetFilesApiV1ImagesVinCodeGetResponse = (Array<(string)>);

export type GetFilesApiV1ImagesVinCodeGetError = (HTTPValidationError);

export type UploadMultipleFilesApiV1ImagesVinCodeMultiplePostData = {
    body: Body_upload_multiple_files_api_v1_images__vin_code__multiple__post;
    path: {
        vin_code: string;
    };
};

export type UploadMultipleFilesApiV1ImagesVinCodeMultiplePostResponse = (MultiImageUploadResponse);

export type UploadMultipleFilesApiV1ImagesVinCodeMultiplePostError = (HTTPValidationError);

export type GetFileApiV1ImagesVinCodeFilenameGetData = {
    path: {
        filename: string;
        vin_code: string;
    };
};

export type GetFileApiV1ImagesVinCodeFilenameGetResponse = (unknown);

export type GetFileApiV1ImagesVinCodeFilenameGetError = (HTTPValidationError);

export type DeleteFileApiV1ImagesVinCodeFilenameDeleteData = {
    path: {
        filename: string;
        vin_code: string;
    };
};

export type DeleteFileApiV1ImagesVinCodeFilenameDeleteResponse = (unknown);

export type DeleteFileApiV1ImagesVinCodeFilenameDeleteError = (HTTPValidationError);

export type RootGetResponse = (unknown);

export type RootGetError = unknown;