// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { CreateNotificationApiV1NotificationPostData, CreateNotificationApiV1NotificationPostError, CreateNotificationApiV1NotificationPostResponse, GetNotificationsApiV1NotificationGetData, GetNotificationsApiV1NotificationGetError, GetNotificationsApiV1NotificationGetResponse, CreateNotificationByAccountantApiV1NotificationAccountantPostData, CreateNotificationByAccountantApiV1NotificationAccountantPostError, CreateNotificationByAccountantApiV1NotificationAccountantPostResponse, CreateNotificationByBrokerApiV1NotificationBrokerPostData, CreateNotificationByBrokerApiV1NotificationBrokerPostError, CreateNotificationByBrokerApiV1NotificationBrokerPostResponse, CreateNotificationAuthApiV1NotificationAuthPostData, CreateNotificationAuthApiV1NotificationAuthPostError, CreateNotificationAuthApiV1NotificationAuthPostResponse, GetNotificationsAllApiV1NotificationAllGetData, GetNotificationsAllApiV1NotificationAllGetError, GetNotificationsAllApiV1NotificationAllGetResponse, GetSingleNotificationApiV1NotificationNotificationIdGetData, GetSingleNotificationApiV1NotificationNotificationIdGetError, GetSingleNotificationApiV1NotificationNotificationIdGetResponse, DeleteNotificationApiV1NotificationNotificationIdDeleteData, DeleteNotificationApiV1NotificationNotificationIdDeleteError, DeleteNotificationApiV1NotificationNotificationIdDeleteResponse, CreateContactApiV1ContactPostData, CreateContactApiV1ContactPostError, CreateContactApiV1ContactPostResponse, GetContactsApiV1ContactGetData, GetContactsApiV1ContactGetError, GetContactsApiV1ContactGetResponse, GetContactApiV1ContactContactIdGetData, GetContactApiV1ContactContactIdGetError, GetContactApiV1ContactContactIdGetResponse, RootGetError, RootGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Create Notification
 */
export const createNotificationApiV1NotificationPost = <ThrowOnError extends boolean = false>(options: Options<CreateNotificationApiV1NotificationPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateNotificationApiV1NotificationPostResponse, CreateNotificationApiV1NotificationPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/notification/'
    });
};

/**
 * Get Notifications
 */
export const getNotificationsApiV1NotificationGet = <ThrowOnError extends boolean = false>(options?: Options<GetNotificationsApiV1NotificationGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetNotificationsApiV1NotificationGetResponse, GetNotificationsApiV1NotificationGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/notification/'
    });
};

/**
 * Create Notification By Accountant
 */
export const createNotificationByAccountantApiV1NotificationAccountantPost = <ThrowOnError extends boolean = false>(options: Options<CreateNotificationByAccountantApiV1NotificationAccountantPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateNotificationByAccountantApiV1NotificationAccountantPostResponse, CreateNotificationByAccountantApiV1NotificationAccountantPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/notification/accountant/'
    });
};

/**
 * Create Notification By Broker
 */
export const createNotificationByBrokerApiV1NotificationBrokerPost = <ThrowOnError extends boolean = false>(options: Options<CreateNotificationByBrokerApiV1NotificationBrokerPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateNotificationByBrokerApiV1NotificationBrokerPostResponse, CreateNotificationByBrokerApiV1NotificationBrokerPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/notification/broker/'
    });
};

/**
 * Create Notification Auth
 */
export const createNotificationAuthApiV1NotificationAuthPost = <ThrowOnError extends boolean = false>(options: Options<CreateNotificationAuthApiV1NotificationAuthPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateNotificationAuthApiV1NotificationAuthPostResponse, CreateNotificationAuthApiV1NotificationAuthPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/notification/auth/'
    });
};

/**
 * Get Notifications All
 */
export const getNotificationsAllApiV1NotificationAllGet = <ThrowOnError extends boolean = false>(options?: Options<GetNotificationsAllApiV1NotificationAllGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetNotificationsAllApiV1NotificationAllGetResponse, GetNotificationsAllApiV1NotificationAllGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/notification/all/'
    });
};

/**
 * Get Single Notification
 */
export const getSingleNotificationApiV1NotificationNotificationIdGet = <ThrowOnError extends boolean = false>(options: Options<GetSingleNotificationApiV1NotificationNotificationIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetSingleNotificationApiV1NotificationNotificationIdGetResponse, GetSingleNotificationApiV1NotificationNotificationIdGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/notification/{notification_id}/'
    });
};

/**
 * Delete Notification
 */
export const deleteNotificationApiV1NotificationNotificationIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteNotificationApiV1NotificationNotificationIdDeleteData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteNotificationApiV1NotificationNotificationIdDeleteResponse, DeleteNotificationApiV1NotificationNotificationIdDeleteError, ThrowOnError>({
        ...options,
        url: '/api/v1/notification/{notification_id}/'
    });
};

/**
 * Create Contact
 */
export const createContactApiV1ContactPost = <ThrowOnError extends boolean = false>(options: Options<CreateContactApiV1ContactPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateContactApiV1ContactPostResponse, CreateContactApiV1ContactPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/contact/'
    });
};

/**
 * Get Contacts
 */
export const getContactsApiV1ContactGet = <ThrowOnError extends boolean = false>(options?: Options<GetContactsApiV1ContactGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetContactsApiV1ContactGetResponse, GetContactsApiV1ContactGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/contact/'
    });
};

/**
 * Get Contact
 */
export const getContactApiV1ContactContactIdGet = <ThrowOnError extends boolean = false>(options: Options<GetContactApiV1ContactContactIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetContactApiV1ContactContactIdGetResponse, GetContactApiV1ContactContactIdGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/contact/{contact_id}/'
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<RootGetResponse, RootGetError, ThrowOnError>({
        ...options,
        url: '/'
    });
};